# Generated by Django 4.2.16 on 2024-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='uploads/default_photo.jpg', upload_to='uploads/'),
        ),
    ]
